name: tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-and-test:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
        os: [ubuntu-latest]

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v1"
        with:
            python-version: "${{ matrix.python-version }}"
      - name: Run CI tests
        run: bash test.sh
        shell: bash
