name: tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-and-test:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
        os: [ubuntu-latest]

    - name: install dependencies [pip]
        run:  |
          pip install --upgrade pip setuptools wheel
          pip install -e .[test]

    - name: unit testing [pytest]
        run: |
          pytest  ${{matrix.test-folder}}
        